idf_component_register(SRCS "vm.c" "frame.c" "thread.c" 
                            "bumper.c" "hashmap.c" "linker.c" 
                            "loader.c" "main.c" "memstream.c" 
                            "preloader.c" "vm.c" "frame.c"
                            "thread.c"
                    INCLUDE_DIRS ".")
