idf_component_register(SRCS "class.c" "monitor.c" "heap.c" "thread.c" "native_methods_service.c" "builtin_classes.c" "loader.c" "init.c" "stringpool.c" "bumper.c" 
                            "parser.c" "main.c" "stream.c" "natives/java/lang/Object.c"
                           
                    INCLUDE_DIRS ".")

