idf_component_register(SRCS "preloader.c" "cfg.c" "frame.c" 
                            "bumper.c" "hashmap.c" "linker.c" 
                            "loader.c" "main.c" "memstream.c" 
                            "preloader.c" "frame.c" "cfg.c"
                            "compiler.c" "IL/interpreter.c"
                    INCLUDE_DIRS ".")

